---
:base_tables:
  - AuditEvent
  - AvailabilityZone
  - BottleneckEvent
  - ChargebackVm
  - ChargebackContainerProject
  - ChargebackContainerImage
  - CloudResourceQuota
  - CloudTenant
  - CloudVolume
  - Compliance
  - ManageIQ::Providers::Foreman::ConfigurationManager::ConfiguredSystem
  - ManageIQ::Providers::ConfigurationManager
  - Container
  - ContainerPerformance
  - ContainerGroup
  - ContainerGroupPerformance
  - ContainerImage
  - ContainerImageRegistry
  - ContainerNode
  - ContainerNodePerformance
  - ContainerProject
  - ContainerProjectPerformance
  - ContainerReplicator
  - ContainerRoute
  - ContainerService
  - ContainerTemplate
  - ManageIQ::Providers::CloudManager
  - EmsCluster
  - EmsClusterPerformance
  - EmsEvent
  - ManageIQ::Providers::InfraManager
  - ExtManagementSystem
  - ExtManagementSystemPerformance
  - Flavor
  - Host
  - HostAggregate
  - HostPerformance
  - MiqGroup
  - MiqRegion
  - MiqRequest
  - MiqServer
  - MiqTemplate
  - MiqWorker
  - OntapFileShare
  - OntapLogicalDisk
  - OntapStorageSystem
  - OntapStorageVolume
  - OntapVolumeMetricsRollup
  - OrchestrationStack
  - OrchestrationTemplate
  - PolicyEvent
  - ResourcePool
  - SecurityGroup
  - Service
  - ServiceTemplate
  - Storage
  - StorageFile
  - StoragePerformance
  - Switch
  - ManageIQ::Providers::CloudManager::Template
  - ManageIQ::Providers::InfraManager::Template
  - Tenant
  - User
  - VimPerformanceTrend
  - Vm
  - ManageIQ::Providers::CloudManager::Vm
  - ManageIQ::Providers::InfraManager::Vm
  - VmPerformance
  - Zone
:include_tables:
  - advanced_settings
  - audit_events
  - availability_zones
  - cloud_networks
  - cloud_resource_quotas
  - cloud_tenants
  - compliances
  - compliance_details
  - computer_systems
  - configuration_profiles
  - configuration_managers
  - configured_systems
  - containers
  - container_groups
  - container_projects
  - container_images
  - container_nodes
  - customization_scripts
  - customization_script_media
  - customization_script_ptables
  - disks
  - ems_events
  - ems_clusters
  - ems_custom_attributes
  - evm_owners
  - event_logs
  - ext_management_systems
  - filesystem_drivers
  - filesystems
  - firewall_rules
  - flavors
  - groups
  - guest_applications
  - guest_devices
  - hardwares
  - hosts
  - host_aggregates
  - host_services
  - kernel_drivers
  - key_pairs
  - lans
  - last_compliances
  - linux_initprocesses
  - miq_actions
  - miq_approval_stamps
  - miq_custom_attributes
  - miq_policy_sets
  - miq_provisions
  - miq_regions
  - miq_requests
  - miq_scsi_luns
  - miq_servers
  - miq_workers
  - ontap_concrete_extents
  - ontap_file_shares
  - ontap_logical_disks
  - ontap_plex_extents
  - ontap_raid_group_extents
  - ontap_storage_systems
  - ontap_storage_volumes
  - openscap_results
  - openscap_rule_results
  - orchestration_stack_outputs
  - orchestration_stack_parameters
  - orchestration_stack_resources
  - orchestration_templates
  - operating_system_flavors
  - partitions
  - ports
  - processes
  - miq_provision_templates
  - miq_provision_vms
  - miq_templates
  - networks
  - nics
  - operating_systems
  - patches
  - registry_items
  - resource_pools
  - security_groups
  - service_templates
  - services
  - snapshots
  - stacks
  - storages
  - storage_adapters
  - storage_files
  - switches
  - tenant_quotas
  - users
  - vms
  - volumes
  - win32_services
  - zones
  - storage_systems
  - file_systems
  - hosted_file_shares
  - file_shares
  - logical_disks
  - storage_volumes
  - base_storage_extents
  - top_storage_extents
:exclude_columns:
  - \"^.*_id$\"
  - \"^id$\"
  - \"^min_derived_storage.*$\"
  - \"^max_derived_storage.*$\"
  - assoc_ids
  - capture_interval
  - filters
  - icon
  - intervals_in_rollup
  - max_cpu_ready_delta_summation
  - max_cpu_system_delta_summation
  - max_cpu_used_delta_summation
  - max_cpu_wait_delta_summation
  - max_derived_cpu_available
  - max_derived_cpu_reserved
  - max_derived_memory_available
  - max_derived_memory_reserved
  - memory_usage
  - min_cpu_ready_delta_summation
  - min_cpu_system_delta_summation
  - min_cpu_used_delta_summation
  - min_cpu_wait_delta_summation
  - min_derived_memory_available
  - min_derived_memory_reserved
  - min_derived_cpu_available
  - min_derived_cpu_reserved
  - min_max
  - options
  - password
  - policy_settings
  - \"^reserved$\"
  - resource_id
  - settings
  - tag_names
  - v_qualified_desc
:exclude_exceptions:
  - capacity_profile_1_memory_per_vm_with_min_max
  - capacity_profile_1_vcpu_per_vm_with_min_max
  - capacity_profile_2_memory_per_vm_with_min_max
  - capacity_profile_2_vcpu_per_vm_with_min_max
  - chain_id
  - guid
  - openscap_id
:tag_classes:
  ManageIQ::Providers::CloudManager: ext_management_system
  EmsCluster: ems_cluster
  ManageIQ::Providers::InfraManager: ext_management_system
  ManageIQ::Providers::ContainerManager: ext_management_system
  ExtManagementSystem: ext_management_system
  Host: host
  MiqGroup: miq_group
  MiqTemplate: miq_template
  ResourcePool: resource_pool
  Service: service
  Storage: storage
  ManageIQ::Providers::CloudManager::Template: miq_template
  ManageIQ::Providers::InfraManager::Template: miq_template
  User: user
  Vm: vm
  VmOrTemplate: vm
  ManageIQ::Providers::CloudManager::Vm: vm
  ManageIQ::Providers::InfraManager::Vm: vm
  ContainerProject: container_project
  ContainerImage: container_image
:exclude_from_relats:
  ManageIQ::Providers::CloudManager:
    - hosts
    - ems_clusters
    - resource_pools
:format_sub_types:
  :boolean:
    :short_name: Boolean
    :title: Enter true or false
  :bytes:
    :short_name: Bytes
    :title: Enter the number of Bytes
    :units:
    - - Bytes
      - :bytes
    - - KB
      - :kilobytes
    - - MB
      - :megabytes
    - - GB
      - :gigabytes
    - - TB
      - :terabytes
  :date:
    :short_name: Date
    :title: Click to Choose a Date
  :datetime:
    :short_name: Date / Time
    :title: Click to Choose a Date / Time
  :float:
    :short_name: Number
    :title: Enter a Number (like 12.56)
  :gigabytes:
    :short_name: Gigabytes
    :title: Enter the number of Gigabytes
  :integer: &1
    :short_name: Integer
    :title: Enter an Integer
  :kbps:
    :short_name: KBps
    :title: Enter the Kilobytes per second
  :kilobytes:
    :short_name: Kilobytes
    :title: Enter the number of Kilobytes
  :megabytes:
    :short_name: Megabytes
    :title: Enter the number of Megabytes
  :mhz: &2
    :short_name: Mhz
    :title: Enter the number of Megahertz
  :numeric_set:
    :short_name: Number List
    :title: Enter a list of numbers separated by commas
  :percent:
    :short_name: Percent
    :title: Enter a Percent (like 12.5)
  :regex:
    :short_name: Regular Expression
    :title: Enter a Regular Expression
  :string: &3
    :short_name: Text String
    :title: Enter a Text String
  :string_set:
    :short_name: String List
    :title: Enter a list of text strings separated by commas
  :decimal: *1
  :fixnum: *1
  :mhz_avg: *2
  :text: *3
